server:
  port: 8080

spring:
  datasource:
    username: root
    password: 2049@root
    url: jdbc:mysql://localhost:3306/fantasy-box?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always

mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.example.entity

#showSql
logging:
  level:
    com:
      example:
        mapper : debug